# Generated by Django 4.2.7 on 2025-08-24 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metric_type', models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('average', 'Average'), ('percentage', 'Percentage'), ('ratio', 'Ratio'), ('trend', 'Trend'), ('score', 'Score')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('calculation_method', models.CharField(choices=[('sql', 'SQL Query'), ('aggregation', 'Django Aggregation'), ('api', 'External API'), ('ml_model', 'ML Model'), ('manual', 'Manual Entry')], max_length=20)),
                ('query', models.TextField(blank=True)),
                ('aggregation_config', models.JSONField(blank=True, default=dict)),
                ('current_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('decimal_places', models.PositiveIntegerField(default=2)),
                ('format_string', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('calculating', 'Calculating'), ('error', 'Error')], default='active', max_length=20)),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
                ('refresh_frequency', models.PositiveIntegerField(default=3600)),
                ('next_refresh', models.DateTimeField(blank=True, null=True)),
                ('chart_type', models.CharField(blank=True, max_length=50)),
                ('chart_config', models.JSONField(blank=True, default=dict)),
                ('enable_alerts', models.BooleanField(default=False)),
                ('alert_threshold_low', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('alert_threshold_high', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_metrics', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_metrics', to='core.organization')),
            ],
            options={
                'db_table': 'analytics_dashboard_metrics',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dashboard_type', models.CharField(choices=[('executive', 'Executive Dashboard'), ('procurement', 'Procurement Dashboard'), ('pricing', 'Pricing Dashboard'), ('supplier', 'Supplier Dashboard'), ('risk', 'Risk Dashboard'), ('custom', 'Custom Dashboard')], max_length=20)),
                ('layout_config', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('auto_refresh', models.BooleanField(default=True)),
                ('refresh_interval', models.PositiveIntegerField(default=300)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='accessible_dashboards', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='core.organization')),
                ('widgets', models.ManyToManyField(blank=True, related_name='dashboards', to='analytics.dashboardmetric')),
            ],
            options={
                'db_table': 'analytics_dashboards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('price_spike', 'Price Spike'), ('price_drop', 'Price Drop'), ('supplier_issue', 'Supplier Issue'), ('contract_expiry', 'Contract Expiry'), ('budget_overrun', 'Budget Overrun'), ('quality_issue', 'Quality Issue'), ('delivery_delay', 'Delivery Delay'), ('compliance_violation', 'Compliance Violation'), ('system_error', 'System Error'), ('metric_threshold', 'Metric Threshold'), ('ml_anomaly', 'ML Anomaly Detection'), ('workflow', 'Workflow Alert'), ('custom', 'Custom Alert')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], default='active', max_length=15)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('price_analysis', 'Price Analysis'), ('spend_analysis', 'Spend Analysis'), ('supplier_performance', 'Supplier Performance'), ('cost_savings', 'Cost Savings'), ('market_intelligence', 'Market Intelligence'), ('risk_assessment', 'Risk Assessment'), ('compliance', 'Compliance Report'), ('custom', 'Custom Report')], max_length=30)),
                ('report_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('dashboard', 'Interactive Dashboard')], default='pdf', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('scheduled', 'Scheduled')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(blank=True, max_length=20)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('total_records', models.PositiveIntegerField(blank=True, null=True)),
                ('summary_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.organization')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'report_type'], name='analytics_r_organiz_0cbe4d_idx'), models.Index(fields=['created_by', '-created_at'], name='analytics_r_created_62c876_idx'), models.Index(fields=['status', '-created_at'], name='analytics_r_status_22fbbe_idx'), models.Index(fields=['is_scheduled', 'next_run'], name='analytics_r_is_sche_941e48_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataQualityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('check_type', models.CharField(choices=[('completeness', 'Completeness Check'), ('accuracy', 'Accuracy Check'), ('consistency', 'Consistency Check'), ('timeliness', 'Timeliness Check'), ('validity', 'Validity Check'), ('uniqueness', 'Uniqueness Check')], max_length=20)),
                ('table_name', models.CharField(max_length=100)),
                ('column_name', models.CharField(blank=True, max_length=100)),
                ('check_query', models.TextField()),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('expected_value', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('warning', 'Warning'), ('running', 'Running'), ('error', 'Error')], default='passed', max_length=15)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('pass_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_scheduled', models.BooleanField(default=True)),
                ('schedule_frequency', models.CharField(default='daily', max_length=20)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('create_alert_on_failure', models.BooleanField(default=True)),
                ('alert_recipients', models.ManyToManyField(blank=True, related_name='dq_alert_recipients', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_quality_checks', to='core.organization')),
            ],
            options={
                'db_table': 'analytics_data_quality_checks',
                'ordering': ['table_name', 'name'],
                'indexes': [models.Index(fields=['organization', 'status'], name='analytics_d_organiz_2217d4_idx'), models.Index(fields=['table_name', 'check_type'], name='analytics_d_table_n_6eff6b_idx'), models.Index(fields=['is_scheduled', 'next_run'], name='analytics_d_is_sche_a6da65_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dashboardmetric',
            index=models.Index(fields=['organization', 'status'], name='analytics_d_organiz_568656_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardmetric',
            index=models.Index(fields=['category', 'metric_type'], name='analytics_d_categor_899c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardmetric',
            index=models.Index(fields=['next_refresh'], name='analytics_d_next_re_c2a921_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdashboard',
            index=models.Index(fields=['organization', 'dashboard_type'], name='analytics_d_organiz_a98821_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdashboard',
            index=models.Index(fields=['created_by', '-created_at'], name='analytics_d_created_781d20_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['organization', 'status', 'severity'], name='analytics_a_organiz_e3bedc_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'status'], name='analytics_a_alert_t_7d307a_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'created_at'], name='analytics_a_severit_44666c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'created_at'], name='analytics_a_status_080afd_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['expires_at'], name='analytics_a_expires_8cf31f_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['source_type', 'source_id'], name='analytics_a_source__b6651a_idx'),
        ),
    ]
