# Production Deployment Configuration for AI Pricing Agent ML Service
version: '3.8'

services:
  ml-service:
    build:
      context: ..
      dockerfile: Dockerfile.fastapi
    image: pricing-agent-ml:latest
    container_name: pricing-ml-service
    
    ports:
      - "8001:8001"
      - "9090:9090"  # Prometheus metrics
    
    environment:
      # Application settings
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8001
      - WORKER_PROCESSES=4
      - MAX_CONNECTIONS=1000
      
      # Database
      - DATABASE_URL=postgresql+asyncpg://pricing_user:${DB_PASSWORD}@postgres:5432/pricing_agent
      
      # Redis
      - REDIS_URL=redis://redis:6379
      - REDIS_TIMEOUT=30
      
      # MLflow
      - MLFLOW_TRACKING_URI=postgresql://mlflow_user:${MLFLOW_DB_PASSWORD}@postgres:5432/mlflow
      - MLFLOW_EXPERIMENT_NAME=pricing_agent_production
      - MLFLOW_ARTIFACT_ROOT=s3://pricing-models/mlflow-artifacts
      
      # Security
      - SECRET_KEY=${SECRET_KEY}
      - ML_SERVICE_JWT_SECRET=${ML_SERVICE_JWT_SECRET}
      
      # Performance
      - MODEL_CACHE_TTL=7200
      - PREDICTION_CACHE_TTL=600
      - FEATURE_CACHE_TTL=1800
      - MAX_BATCH_SIZE=1000
      
      # Monitoring
      - ENABLE_METRICS=true
      - METRICS_PORT=9090
      - LOG_LEVEL=INFO
      - STRUCTURED_LOGGING=true
      
      # Rate limiting
      - RATE_LIMIT_ENABLED=true
      - RATE_LIMIT_REQUESTS_PER_MINUTE=100
      - RATE_LIMIT_BURST=20
      
      # External services
      - DJANGO_SERVICE_URL=http://django-app:8000
      - MARKET_DATA_ENABLED=true
      - MARKET_DATA_API_KEY=${MARKET_DATA_API_KEY}
    
    volumes:
      - ml-models:/app/ml_artifacts/models
      - ml-logs:/app/logs
      - /etc/ssl/certs:/etc/ssl/certs:ro  # SSL certificates
    
    depends_on:
      - postgres
      - redis
      - mlflow-server
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    restart: unless-stopped
    
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    
    networks:
      - pricing-network
    
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  mlflow-server:
    image: mlflow/mlflow:2.7.1
    container_name: mlflow-server
    
    ports:
      - "5000:5000"
    
    environment:
      - BACKEND_STORE_URI=postgresql://mlflow_user:${MLFLOW_DB_PASSWORD}@postgres:5432/mlflow
      - DEFAULT_ARTIFACT_ROOT=s3://pricing-models/mlflow-artifacts
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    
    command: >
      mlflow server
      --backend-store-uri postgresql://mlflow_user:${MLFLOW_DB_PASSWORD}@postgres:5432/mlflow
      --default-artifact-root s3://pricing-models/mlflow-artifacts
      --host 0.0.0.0
      --port 5000
    
    depends_on:
      - postgres
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    restart: unless-stopped
    networks:
      - pricing-network

  postgres:
    image: timescale/timescaledb:2.11.2-pg15
    container_name: postgres-pricing
    
    ports:
      - "5432:5432"
    
    environment:
      - POSTGRES_DB=pricing_agent
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PRICING_USER_PASSWORD=${DB_PASSWORD}
      - MLFLOW_USER_PASSWORD=${MLFLOW_DB_PASSWORD}
    
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pricing_agent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    
    restart: unless-stopped
    networks:
      - pricing-network

  redis:
    image: redis:7-alpine
    container_name: redis-pricing
    
    ports:
      - "6379:6379"
    
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 64mb
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru
    
    volumes:
      - redis-data:/data
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    
    restart: unless-stopped
    networks:
      - pricing-network

  # Monitoring stack
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    
    ports:
      - "9091:9090"
    
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    
    restart: unless-stopped
    networks:
      - pricing-network

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    
    ports:
      - "3001:3000"
    
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    
    depends_on:
      - prometheus
    
    restart: unless-stopped
    networks:
      - pricing-network

  # Load balancer/reverse proxy
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx-pricing
    
    ports:
      - "80:80"
      - "443:443"
    
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx-logs:/var/log/nginx
    
    depends_on:
      - ml-service
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    restart: unless-stopped
    networks:
      - pricing-network

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  ml-models:
    driver: local
  ml-logs:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  nginx-logs:
    driver: local

networks:
  pricing-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16