# Generated by Django 4.2.7 on 2025-08-24 01:18

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        ('pricing', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.category'),
        ),
        migrations.AddField(
            model_name='material',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.organization'),
        ),
        migrations.AddField(
            model_name='costmodel',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_models', to='pricing.material'),
        ),
        migrations.AddField(
            model_name='costmodel',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_categories', to='core.organization'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pricing.category'),
        ),
        migrations.AddIndex(
            model_name='pricebenchmark',
            index=models.Index(fields=['material', 'benchmark_type', '-period_end'], name='price_bench_materia_7d7708_idx'),
        ),
        migrations.AddIndex(
            model_name='pricebenchmark',
            index=models.Index(fields=['organization', '-period_end'], name='price_bench_organiz_6a4c80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricebenchmark',
            unique_together={('material', 'organization', 'benchmark_type', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['user', 'status'], name='price_alert_user_id_82c832_idx'),
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['material', 'status'], name='price_alert_materia_7d0bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['material', '-time'], name='prices_materia_6f4993_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['supplier', '-time'], name='prices_supplie_53ce0c_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['organization', 'price_type', '-time'], name='prices_organiz_e0082f_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['price_type', '-time'], name='prices_price_t_1842cd_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['valid_from', 'valid_to'], name='prices_valid_f_5df840_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['organization', 'status'], name='materials_organiz_5c2f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['category', 'material_type'], name='materials_categor_dfd895_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['code'], name='materials_code_1ed4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=django.contrib.postgres.indexes.GinIndex(fields=['specifications'], name='materials_specifi_318925_gin'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=django.contrib.postgres.indexes.GinIndex(fields=['attributes'], name='materials_attribu_0e4518_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='costmodel',
            unique_together={('material', 'name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('organization', 'name')},
        ),
    ]
