# Generated by Django 5.0.1 on 2025-08-28 23:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/procurement/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["csv", "xlsx", "xls", "parquet"]
                            )
                        ],
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("xlsx", "Excel (XLSX)"),
                            ("xls", "Excel (XLS)"),
                            ("parquet", "Parquet"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        validators=[django.core.validators.MaxValueValidator(52428800)]
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("purchase_orders", "Purchase Orders"),
                            ("invoices", "Invoices"),
                            ("contracts", "Contracts"),
                            ("suppliers", "Supplier Master"),
                            ("materials", "Material Master"),
                            ("spend_data", "Spend Analysis"),
                            ("price_history", "Historical Prices"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("validating", "Validating"),
                            ("mapping", "Mapping Columns"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partially Processed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("warnings", models.JSONField(default=list)),
                ("total_rows", models.IntegerField(default=0)),
                ("processed_rows", models.IntegerField(default=0)),
                ("failed_rows", models.IntegerField(default=0)),
                ("duplicate_rows", models.IntegerField(default=0)),
                (
                    "detected_schema",
                    models.JSONField(
                        default=dict, help_text="Auto-detected column schema"
                    ),
                ),
                (
                    "column_mapping",
                    models.JSONField(
                        default=dict, help_text="User-confirmed column mappings"
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        default=dict, help_text="Applied validation rules"
                    ),
                ),
                (
                    "validation_report",
                    models.JSONField(
                        default=dict, help_text="Detailed validation results"
                    ),
                ),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "processing_duration_seconds",
                    models.IntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataIngestionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("upload_started", "Upload Started"),
                            ("validation_completed", "Validation Completed"),
                            ("mapping_saved", "Mapping Saved"),
                            ("processing_started", "Processing Started"),
                            ("processing_completed", "Processing Completed"),
                            ("error_occurred", "Error Occurred"),
                            ("manual_correction", "Manual Correction"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(default=dict)),
                ("rows_affected", models.IntegerField(default=0)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="data_ingestion.dataupload",
                    ),
                ),
            ],
            options={
                "ordering": ["upload", "-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ProcurementDataStaging",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row_number", models.IntegerField()),
                (
                    "raw_data",
                    models.JSONField(help_text="Original row data as uploaded"),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Validation"),
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("corrected", "Corrected"),
                            ("ignored", "Ignored"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("validation_errors", models.JSONField(default=list)),
                ("validation_warnings", models.JSONField(default=list)),
                (
                    "po_number",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=50)),
                ("line_item_number", models.CharField(blank=True, max_length=20)),
                ("supplier_name", models.CharField(blank=True, max_length=255)),
                (
                    "supplier_code",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("supplier_site", models.CharField(blank=True, max_length=100)),
                (
                    "material_code",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("material_description", models.TextField(blank=True)),
                ("material_category", models.CharField(blank=True, max_length=100)),
                ("material_group", models.CharField(blank=True, max_length=100)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                ("unit_of_measure", models.CharField(blank=True, max_length=20)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "purchase_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("buyer_name", models.CharField(blank=True, max_length=100)),
                ("cost_center", models.CharField(blank=True, max_length=50)),
                ("gl_account", models.CharField(blank=True, max_length=50)),
                ("project_code", models.CharField(blank=True, max_length=50)),
                ("is_duplicate", models.BooleanField(default=False)),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data_ingestion.procurementdatastaging",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staging_records",
                        to="data_ingestion.dataupload",
                    ),
                ),
            ],
            options={
                "ordering": ["upload", "row_number"],
            },
        ),
        migrations.CreateModel(
            name="DataMappingTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("purchase_orders", "Purchase Orders"),
                            ("invoices", "Invoices"),
                            ("contracts", "Contracts"),
                            ("suppliers", "Supplier Master"),
                            ("materials", "Material Master"),
                            ("spend_data", "Spend Analysis"),
                            ("price_history", "Historical Prices"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        blank=True, help_text="e.g., SAP, Oracle, Coupa", max_length=100
                    ),
                ),
                ("column_mappings", models.JSONField(default=dict)),
                (
                    "transformations",
                    models.JSONField(
                        default=dict,
                        help_text="Field-level transformations (e.g., date formats, currency conversion)",
                    ),
                ),
                ("validation_rules", models.JSONField(default=dict)),
                ("times_used", models.IntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-times_used", "name"],
                "unique_together": {("organization", "name")},
            },
        ),
        migrations.AddIndex(
            model_name="dataupload",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="data_ingest_organiz_017472_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataupload",
            index=models.Index(
                fields=["status", "organization"], name="data_ingest_status_ce1816_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataupload",
            index=models.Index(
                fields=["data_type", "organization"],
                name="data_ingest_data_ty_eaafd2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataingestionlog",
            index=models.Index(
                fields=["upload", "-timestamp"], name="data_ingest_upload__822bfc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="procurementdatastaging",
            index=models.Index(
                fields=["upload", "validation_status"],
                name="data_ingest_upload__a4fb8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="procurementdatastaging",
            index=models.Index(
                fields=["supplier_code", "material_code"],
                name="data_ingest_supplie_467b77_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="procurementdatastaging",
            index=models.Index(
                fields=["purchase_date"], name="data_ingest_purchas_a1a1f2_idx"
            ),
        ),
    ]
