# Generated by Django 5.0.1 on 2025-08-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataupload",
            name="celery_task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for async processing",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="dataupload",
            name="processing_progress",
            field=models.IntegerField(
                default=0, help_text="Processing progress percentage"
            ),
        ),
    ]
