# Generated by Django 5.0.7 on 2025-12-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_ingestion", "0002_dataupload_celery_task_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataupload",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("validating", "Validating"),
                    ("mapping", "Mapping Columns"),
                    ("ready_to_process", "Ready to Process"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("partial", "Partially Processed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
