# Generated by Django 5.0.7 on 2025-12-29 05:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_ingestion", "0003_alter_dataupload_status"),
        ("pricing", "0002_initial"),
        ("procurement", "0002_purchaseorder_purchaseorderline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchingConflict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("supplier", "Supplier Match"),
                            ("material", "Material Match"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("resolved_match", "Confirmed as Match"),
                            ("resolved_new", "Confirmed as New"),
                            ("auto_resolved", "Auto-Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("incoming_value", models.CharField(max_length=255)),
                (
                    "incoming_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("potential_matches", models.JSONField(default=list)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("highest_similarity", models.FloatField(default=0.0)),
                ("auto_resolve_threshold", models.FloatField(default=0.95)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "matched_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pricing.material",
                    ),
                ),
                (
                    "matched_supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="procurement.supplier",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staging_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="data_ingestion.procurementdatastaging",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="data_ingestion.dataupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-highest_similarity", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["upload", "status"],
                        name="data_ingest_upload__8c6e0f_idx",
                    ),
                    models.Index(
                        fields=["conflict_type", "status"],
                        name="data_ingest_conflic_c6db96_idx",
                    ),
                ],
            },
        ),
    ]
