# Generated by Django 5.0.7 on 2025-12-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_ingestion", "0004_matchingconflict"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataupload",
            name="data_quality_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Overall data quality score (0-100)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
